### PR TITLE
Add floaxie implementation

### PR DESCRIPTION
**Pull request by aclex**
Would be so glad, if you could add my another Grisu2 implementation, in Floaxie library (https://github.com/aclex/floaxie), to the benchmark.

At first, I'd like to say a big thank you to @miloyip as it's so much inspired of his implementation. The aim was to implement Grisu2 on most modern C++14, but the most significant feature of the library itself is an algorithm (which I called Krosh) for reciprocal task of fast parsing floating point text representations based on the principles of Grisu algorithms.

### CODE REVIEW

**Comment by aclex** [comment]
Thank you very much for merging!

**Comment by vitaut** [comment]
This fails to compile:

```
floaxietest.cpp
In file included from ../../src/floaxietest.cpp:2:
In file included from ../../src/floaxie/ftoa.h:26:
In file included from ../../src/floaxie/grisu.h:36:
In file included from ../../src/floaxie/diy_fp.h:34:
../../src/floaxie/bit_ops.h:42:33: error: unknown type name 'constexpr'
        template<typename NumericType> constexpr std::size_t bit_size() noexcept
                                       ^
```

You might need to enable C++11/14 somewhere in the build config.

**Comment by aclex** [comment]
@vitaut Yes, it depends on C++14. I obviously overseen this due to testing on recent GCC versions, which imply C++14 mode by default. I'll look at this to find a way to skip floaxie if building with pre-C++14 modes to fix this.

**Comment by aclex** [comment]
Just added a little fix in #14 to solve the regression, hopefully, it would help. Many thanks to @vitaut for pointing out!

**Pull request merged**
